[build]
  publish = "public"
  functions = "netlify/functions"

[dev]
  command = "netlify dev"
  port = 8888
  targetPort = 8888

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
